# Generated by Django 4.1.4 on 2022-12-18 00:35

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Sensors",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sensor_type", models.CharField(max_length=200)),
                ("address", models.CharField(max_length=400)),
                ("date", models.DateField()),
                ("time", models.DateTimeField()),
                ("measure", models.FloatField(max_length=10)),
                (
                    "coordinates",
                    django.contrib.gis.db.models.fields.PointField(srid=4326),
                ),
                ("unit", models.FloatField(max_length=10)),
                ("user_id", models.CharField(max_length=200)),
            ],
        ),
    ]
