# Generated by Django 4.1.4 on 2022-12-26 00:05

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("playground", "0002_alter_sensors_unit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sensors",
            name="coordinates",
            field=django.contrib.gis.db.models.fields.PointField(
                blank=True, null=True, srid=4326
            ),
        ),
    ]
